version: "3"

networks:
  backend:
  frontend:

services:
  business-api:
    build: .
    image: business-api:latest

  keycloak:
    image: jboss/keycloak:10.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: mysql
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_PORT: "3306"
      DB_DATABASE: keycloak
      KEYCLOAK_IMPORT: /tmp/import-realm.json
    ports:
      - 8080:8080
    volumes:
      - ./keycloak:/tmp
    networks:
      - backend
      - frontend

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend
      - frontend